sudo: false
language: node_js
node_js:
- '8'
script:
- npm run lint
- npm run lint:style
- npm run test
- npm run build
jobs:
  include:
    stage: Deploy
    script:
    - npm run build
    deploy:
      provider: heroku
      app: homework-nodejs-preview
      api_key:
        secure: SMt/tsHMVQj4RknPmmxcZkYnnPbO1vZRl2SEgiXLn2lEaJzliQcSq48g4HA1P6RJM32L45Ye8cvkPrNXWCoqnRX4iT/AmurLyKa68PJrTqiodbAlbyD4qukRvo1dzHrALKvfws7uoMpwMDvkyD8Lo15l/d7I7XCHO4m4+TsTVu4PtOH/yuBrpL2SlaBe5z68IMbTq/6GC9x9z5DkmeInsTIuBFZxBg9lNQ5qQf0GY4waVlJFs1xgW3r+Lj3RvYmagZ8znhiSyr+qlEJq2bTblFzFvhEHLumERRjk66t2MX/+wgujc/1z0SzpUBwtm13OKKC6NGsB8hp3JdSRrhTtUloC76T32TKSpVqpDb5UeGjEWYH7RabEuicL8VxDbtMfHqqarCFg9Pd4CrNIucTefK8ziFEbmC9SJOuMF1V+3U5W4oUCxTOmGj1ikR2t6XEdfHSverTOlzcaMUFdY9Ymz9uYr3chV7y2Ud5lr8zeuPg8mpnBrew6Sc3AxaFiQDlwdd3IvqYosURQJLiCZzC+YbWhZ8y+SMh95dAIP2ejJTQQ1uuykIbxZ82CzSWx+y2AyE7xridSsnUXiOp7JTRJMm0toc0ECBKD4dx1LUGFRn+UPXfXCVNvUrFplFhuMmVIL967HB+fgS3uy9uqn83L/hxq6KarFE5Ybe9up+1GE+w=
      skip_cleanup: true
      on:
        all_branches: true
env:
  global:
    secure: UxyJjVBUyz4DRy73DCHpKDBe+vwlkf5SlhjXblFdQA2HwaQFswGs7RKx8hbSQEuHUGw0cQg8blOd2+7fq4lpPSI52XX614d9zDjZPlBMGCHdLwjFmq37Zf6WH75zxQa4YjXHcPs2C/S2K/Z7SdK4coR8kf0J6+jwMQIgbNA3rZWvru6t9brdI68x9ZDnFkXUuhixOeTWe0T+Ravaqn+7gVdqdt10Iyat2Uf28pnyLKj2oP33Fe7qNxzbcfTTHmnMI8D/3FOQ4GyotSNg2aZy9tIXOd8r6mqMIKQtUd5YnwFG8L1DTWwHCj8M1303iqi78xxAEC/YoxknmfwmAgXa+RUEriAENcsZ5l+u8+1QuPMpafphpuQXEc6+AYlmej91Zc7ya1j85GZRcfgyW57QPSUQPgfhbeyUbwr1tNlZgu72HLwNi9Hk2Hjx9rvkcyTmlhyOewJkUzJ7YxMsTinN7WaoTYTBAGqryugjb4Ck4101JPa7H7BCdX9rBXBuCKScfIzU33KmOGz0F7orhLZ1lKr6Xtwn8QHcLotflpZ3N/GFwpPB5LYBg4DwHahyWfq3V7JfXtyrWkxZGB2fomVji+C08zMV9AyGsLfrqz3zFDFMurmxHsn5OyVUDfoHatZc0ys2D9rTgJd/JyXHFtkk098QqZeVzESgmz8uU/9GPhw=
