sudo: false
language: node_js
node_js:
- '8'
script:
- npm run lint
- npm run lint:style
- npm run test
- npm run build
jobs:
  include:
    stage: Deploy
    script:
    - npm run build
    deploy:
      provider: heroku
      app: homework-nodejs
      api_key:
        secure: KYQwX0tfU86XX0MajprEum3mdvJqCq3iu+phut2hzLVGcFT2FXBq2MKW+fpB2NrXCnsV8P4W500jZcTfQaWQ0VaAppIfhZPrK+zRxLQHvTxNGGdMfAs6jiVHaqsO0Wh0fP5i6zJTsyuOJMJ+tF1yNewuz+AI7G54F3Mr2NSztTxi9mYxIitbfOIBk14mknDXLddF2qCkq7hmJU/NSHnwvNvx4SqC78i1RqOAlF7XPugrvoZ7dv9kF3at/hgCMhwMeaXztpwMV0xVbrX5aO/ZV8+2TDtjHe/FhYw+LtXAMEg7ZBIg/lxu3ITLzTrI+yrdw0EtZLXuLjeczqjDwdw2QtI2aI/5EGd/gUxQ6LC0f7Pqx/DZS12Hks30vZnK7idMCWvPZc3hsZop2f/I/9JdmASJGDQhNP/mRaPU0tukfJLVJJoN+Gab1n/kY+SpdhqN/wcbpNSGpnbFn5MB0yQVVQ3BcE+Asr/u6U69WnJKSslMO6JbKBJHWQoQtPD/pR5tADdgzAvV2JgZKdKW7DOh3OD8MCyrrlq8vEscVlX2V1l9msdWngu1XskSDddUzRTod1ME32/RS+ghgRCFu7D7FESJEquUZQNt9S8IA7R1HTFdvDqSMen86DI08ZX/k4rc/6sVbqesIVI2x9wXVHht8LC4g410N6Omye5+hxQPDHI=
      skip_cleanup: true
      on:
        all_branches: true
